[target.aarch64-unknown-linux-musl]
pre-build = [
    "apt-get update -y",
    "apt-get install -y --no-install-recommends libc6-dev"
]

[env]
RUSTFLAGS = "-C opt-level=3 -C codegen-units=1 -C panic=abort"
